# 1. Create a null vector of size 10 but the fifth value which is 1.

In [1]:
import numpy as np
arr=np.zeros(10)
arr[5]=1
arr

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

# 2. Create a vector with values ranging from 10 to 49.

In [7]:
arr=np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# 3. Create a 3x3 matrix with values ranging from 0 to 8

In [13]:
arr=np.arange(0,9)
arr1=arr.reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [19]:
arr= np.array([1,2,0,0,4,0])
arr1= np.where(arr>0)
print("Indice of non-zero elements are:",arr1)

Indice of non-zero elements are: (array([0, 1, 4], dtype=int64),)


In [26]:
arr= np.array([1,2,0,0,4,0])
print("Indice of non-zero elements are:")
for i in range (len(arr)):
    if arr[i] !=0:
        print(i,end=",")

Indice of non-zero elements are:
0,1,4,

# 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [34]:
#Random Value
arr=np.random.randint(0,100,(10,10))
print("Random Value:",arr)
#Maximum Value
arr1=np.max(arr)
print("The maxium value is:",arr1)
#Minimum Value
arr2=np.min(arr)
print("The minium value is:",arr2)

Random Value: [[89 36  6 45 98 85  9 40 53 16]
 [99 95 88 87 92  6 94 13 43 23]
 [ 1  0 40 45 89 87 86 15  7 20]
 [23 69 30 65 50  1 96 78 22  8]
 [91 76 35 67 43 86 90 12 12 48]
 [50 63 38 14 45 32 49 25 92 18]
 [36 44 13  9  7 57 18 59 72 20]
 [84 20 64 23 61 33 14 37  0 84]
 [15 17 85 83 23 75 63 92 65 15]
 [47  6 58 29  9 56 37 59  6 14]]
The maxium value is: 99
The minium value is: 0


# 6. Create a random vector of size 30 and find the mean value.

In [35]:
arr=np.random.rand(30)
arr1=arr.mean()
arr1

0.5289634077315084

In [39]:
arr=np.random.randint(2,30,90)
arr1=arr.mean()
arr1

15.933333333333334